console.log(a+b);
// console.log(a-b);
// console.log(a*b);
// console.log(a/b);
// console.log(a%b);
// console.log(++a);
// console.log(a++);
// console.log(--b);
// console.log(b--);
// console.log(a);
// console.log(b);
// console.log(a+=3);
// console.log(a-=3);
// console.log(a*=3);
// console.log(a/=3);
// console.log(a%=3);